baseURL: "https://aarontech.xyz/"
title: AaronTech
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-9LDB5P3D3T
disqusShortname: aarontech
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: AaronTech
  description: "A blog by Aaron -- a student in Taiwan"
  keywords: [Blog, Portfolio, Personal Website, AaronTech, Aaron, Taiwan, Tech]
  author: Me
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.png"
    favicon16x16: "/favicon.png"
    favicon32x32: "/favicon.png"
    apple_touch_icon: "/favicon.png"
    safari_pinned_tab: "/favicon.png"

  label:
    text: "Home"
    icon: /favicon.png
    iconHeight: 40

  profileMode:
    enabled: false
    title: AaronTech
    subtitle: "A blog by Aaron -- a student in Taiwan"
    imageUrl: "/favicon.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my profile picture
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B, I'm Aaron"
    Subtitle: "A student from Taiwan"
    Content: "Fun fact: I constantly swear while writing code"

  socialIcons:
    - name: github
      url: "https://github.com/aaronleetw"
    - name: instagram
      url: "https://instagram.com/aaronleetw"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/15017153/he110w0r1d"
    - name: twitter
      url: "https://twitter.com/helloworld_tw_"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/aaronleetw/aaronlee.live/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
outputs:
    home:
        - HTML
        - RSS
        - JSON
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 15
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 25
    - identifier: projects
      name: projects
      url: /projects/
      weight: 30
